# Site settings
title:          Tiantian's footsteps
description:    "Stories about my learning path"
url:            "https://supperac.github.io"

# Author
author:
  name:         Tiantian Lu
  url:          https://www.linkedin.com/in/tiantianlu
  email:        tiantianlu91@hotmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
